// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoxazjpmlmntrcrsouhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVveGF6anBtbG1udHJjcnNvdWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzcwMjksImV4cCI6MjA2MTk1MzAyOX0.AcFN_gbxnxBwT2UcFcVQcAzx-Og7Ipf0sy0BbR5Njvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);